/**
 * Native fingerprint used as the beta runtime version (`app.config.ts`).
 * `/beta-build` publishes an OTA update when HEAD's fingerprint matches the
 * latest TestFlight beta build, and builds natively otherwise.
 *
 * Skip inputs that change without touching native code, so JS-only commits stay
 * OTA-compatible: `extra` carries the commit hash, versions change on every
 * release bump, and package.json scripts/.gitignore never reach Xcode.
 *
 * `@bacons/apple-targets` sources and alternate icons are not detected
 * automatically, so hash them explicitly.
 *
 * @type {import('expo/fingerprint').Config}
 */
const { SourceSkips } = require('expo/fingerprint')

module.exports = {
  sourceSkips:
    SourceSkips.ExpoConfigRuntimeVersionIfString |
    SourceSkips.ExpoConfigVersions |
    SourceSkips.ExpoConfigExtraSection |
    SourceSkips.PackageJsonScriptsAll |
    SourceSkips.GitIgnore,
  extraSources: [
    { type: 'dir', filePath: 'targets', reasons: ['appleTargets'] },
    { type: 'dir', filePath: 'src/assets/icons', reasons: ['alternateIcons'] },
  ],
  // Regenerated by prebuild from the (hashed) target config and app icon, so
  // they differ between a worktree and the build machine.
  ignorePaths: [
    'targets/*/generated.entitlements',
    'targets/*/Assets.xcassets/**',
  ],
}
