/**
 * Native fingerprint used as the beta runtime version (`app.config.ts`).
 * `/beta-build` publishes an OTA update when HEAD's fingerprint matches the
 * latest TestFlight beta build, and builds natively otherwise.
 *
 * Skip inputs that change without touching native code, so JS-only commits stay
 * OTA-compatible: `extra` carries the commit hash, versions change on every
 * release bump, and package.json scripts/.gitignore never reach Xcode.
 *
 * `@bacons/apple-targets` sources, alternate icons, and Android menu drawables
 * are not detected automatically, so hash them explicitly.
 *
 * @type {import('expo/fingerprint').Config}
 */
const { SourceSkips } = require('expo/fingerprint')

module.exports = {
  sourceSkips:
    SourceSkips.ExpoConfigRuntimeVersionIfString |
    SourceSkips.ExpoConfigVersions |
    SourceSkips.ExpoConfigExtraSection |
    SourceSkips.PackageJsonScriptsAll |
    SourceSkips.GitIgnore,
  extraSources: [
    { type: 'dir', filePath: 'targets', reasons: ['appleTargets'] },
    { type: 'dir', filePath: 'src/assets/icons', reasons: ['alternateIcons'] },
    {
      type: 'dir',
      filePath: 'src/assets/android-menu-icons',
      reasons: ['androidMenuIcons'],
    },
  ],
  ignorePaths: [
    // Regenerated by prebuild from the (hashed) target config and app icon, so
    // they differ between a worktree and the build machine.
    'targets/*/generated.entitlements',
    'targets/*/Assets.xcassets/**',
    // The Wear OS app is its own APK; it never changes the phone app's binary.
    'targets/wear-os/**',
    // react-native-maps' Xcode build phase rewrites this from whether the
    // GoogleMaps pods are installed (decided by hashed config), so it is a
    // build output; hashing it would change the runtime version after a build.
    'node_modules/react-native-maps/ios/AirMaps/RNMapsDefines.h',
    // app.config.ts imports it for permission strings, which the hashed Expo
    // config already carries; hashing the whole file made every new UI string
    // a native change.
    'src/locales/en-US.json',
  ],
}
