import { useState } from 'react'
import { View } from 'react-native'
import { FlashList } from '@shopify/flash-list'
import {
  ExternalLink as ExternalLinkIcon,
  Search as SearchIcon,
} from 'lucide-react-native'
import { Input, InputProps } from 'tamagui'
import Wrapper from '@/components/ui/layout/Wrapper'
import Text from '@/components/ui/MyText'
import LucideIcon from '@/components/ui/LucideIcon'
import IconButton from '@/components/ui/IconButton'
import Section from '@/components/ui/inputs/Section'
import InputRowButton from '@/features/settings/components/inputs/InputRowButton'
import SettingsInputLayout from '@/features/settings/components/shared/SettingsInputLayout'
import useTheme from '@/contexts/theme'
import i18n from '@/lib/locales'
import { openURL } from '@/lib/links'
import openSourceLicenses from '@/features/settings/constants/openSourceLicenses.json'

type OpenSourcePackage = {
  name: string
  version: string
  license: string
  author?: string
}

const packages: OpenSourcePackage[] = openSourceLicenses

const packageUrl = ({ name, version }: OpenSourcePackage) =>
  `https://www.npmjs.com/package/${name}/v/${version}`

const packageDetails = ({ version, license, author }: OpenSourcePackage) =>
  [version, license === 'Unknown' ? undefined : license, author]
    .filter(Boolean)
    .join(' · ')

/**
 * Credits the open-source packages WitnessWork is built with. Generated by
 * `pnpm licenses:generate`; each row links to the package's license and
 * source.
 */
const OpenSourceLicensesScreen = () => {
  const theme = useTheme()
  const [search, setSearch] = useState('')

  const query = search.trim().toLowerCase()
  const results = query
    ? packages.filter((pkg) =>
        [pkg.name, pkg.license, pkg.author ?? ''].some((value) =>
          value.toLowerCase().includes(query)
        )
      )
    : packages

  return (
    <SettingsInputLayout>
      <Wrapper insets='bottom'>
        <View style={{ gap: 16, paddingTop: 24, paddingBottom: 16 }}>
          <Text style={{ color: theme.colors.textAlt, lineHeight: 22 }}>
            {i18n.t('openSourceLicenses_description', {
              packages: packages.length.toLocaleString(),
            })}
          </Text>
          <View
            style={{
              flexDirection: 'row',
              alignItems: 'center',
              gap: 10,
              paddingHorizontal: 12,
              minHeight: 44,
              borderRadius: theme.numbers.borderRadiusMd,
              borderWidth: 1,
              borderColor: theme.colors.border,
              backgroundColor: theme.colors.backgroundLighter,
            }}
          >
            <LucideIcon
              icon={SearchIcon}
              size={theme.fontSize('xs')}
              style={{ color: theme.colors.textAlt }}
            />
            <Input
              unstyled
              value={search}
              onChangeText={setSearch}
              placeholder={i18n.t('search')}
              placeholderTextColor={
                theme.colors.textAlt as InputProps['placeholderTextColor']
              }
              clearButtonMode='while-editing'
              enterKeyHint='search'
              autoCorrect={false}
              autoCapitalize='none'
              style={{
                flex: 1,
                color: theme.colors.text,
                fontFamily: theme.fonts.regular,
                fontSize: theme.fontSize('md'),
              }}
            />
          </View>
        </View>
        {results.length ? (
          <Section animateRows={false} style={{ flex: 1, marginBottom: 16 }}>
            <FlashList
              data={results}
              keyExtractor={(pkg) => `${pkg.name}@${pkg.version}`}
              keyboardDismissMode='on-drag'
              renderItem={({ item, index }) => (
                <InputRowButton
                  label={item.name}
                  sublabel={packageDetails(item)}
                  onPress={() => openURL(packageUrl(item))}
                  url={packageUrl(item)}
                  lastInSection={index === results.length - 1}
                >
                  <IconButton icon={ExternalLinkIcon} />
                </InputRowButton>
              )}
            />
          </Section>
        ) : (
          <Text
            style={{
              color: theme.colors.textAlt,
              textAlign: 'center',
              paddingTop: 24,
            }}
          >
            {i18n.t('openSourceLicenses_noResults')}
          </Text>
        )}
      </Wrapper>
    </SettingsInputLayout>
  )
}

export default OpenSourceLicensesScreen
