export type Hemisphere = 'north' | 'south' | 'tropical'
export type Season = 'spring' | 'summer' | 'fall' | 'winter'

export const COUNTRY_HEMISPHERE: Record<string, Hemisphere> = {
  AD: 'north',
  AE: 'north',
  AF: 'north',
  AG: 'tropical',
  AI: 'tropical',
  AL: 'north',
  AM: 'north',
  AO: 'south',
  AQ: 'south',
  AR: 'south',
  AS: 'south',
  AT: 'north',
  AU: 'south',
  AW: 'tropical',
  AX: 'north',
  AZ: 'north',
  BA: 'north',
  BB: 'tropical',
  BD: 'north',
  BE: 'north',
  BF: 'tropical',
  BG: 'north',
  BH: 'north',
  BI: 'tropical',
  BJ: 'tropical',
  BL: 'tropical',
  BM: 'north',
  BN: 'tropical',
  BO: 'south',
  BQ: 'tropical',
  BR: 'tropical',
  BS: 'north',
  BT: 'north',
  BV: 'south',
  BW: 'south',
  BY: 'north',
  BZ: 'tropical',
  CA: 'north',
  CC: 'tropical',
  CD: 'tropical',
  CF: 'tropical',
  CG: 'tropical',
  CH: 'north',
  CI: 'tropical',
  CK: 'south',
  CL: 'south',
  CM: 'tropical',
  CN: 'north',
  CO: 'tropical',
  CR: 'tropical',
  CU: 'north',
  CV: 'tropical',
  CW: 'tropical',
  CX: 'tropical',
  CY: 'north',
  CZ: 'north',
  DE: 'north',
  DJ: 'tropical',
  DK: 'north',
  DM: 'tropical',
  DO: 'tropical',
  DZ: 'north',
  EC: 'tropical',
  EE: 'north',
  EG: 'north',
  EH: 'north',
  ER: 'tropical',
  ES: 'north',
  ET: 'tropical',
  FI: 'north',
  FJ: 'south',
  FK: 'south',
  FM: 'tropical',
  FO: 'north',
  FR: 'north',
  GA: 'tropical',
  GB: 'north',
  GD: 'tropical',
  GE: 'north',
  GF: 'tropical',
  GG: 'north',
  GH: 'tropical',
  GI: 'north',
  GL: 'north',
  GM: 'tropical',
  GN: 'tropical',
  GP: 'tropical',
  GQ: 'tropical',
  GR: 'north',
  GS: 'south',
  GT: 'tropical',
  GU: 'tropical',
  GW: 'tropical',
  GY: 'tropical',
  HK: 'north',
  HM: 'south',
  HN: 'tropical',
  HR: 'north',
  HT: 'tropical',
  HU: 'north',
  ID: 'tropical',
  IE: 'north',
  IL: 'north',
  IM: 'north',
  IN: 'north',
  IO: 'tropical',
  IQ: 'north',
  IR: 'north',
  IS: 'north',
  IT: 'north',
  JE: 'north',
  JM: 'tropical',
  JO: 'north',
  JP: 'north',
  KE: 'tropical',
  KG: 'north',
  KH: 'tropical',
  KI: 'tropical',
  KM: 'tropical',
  KN: 'tropical',
  KP: 'north',
  KR: 'north',
  KW: 'north',
  KY: 'tropical',
  KZ: 'north',
  LA: 'tropical',
  LB: 'north',
  LC: 'tropical',
  LI: 'north',
  LK: 'tropical',
  LR: 'tropical',
  LS: 'south',
  LT: 'north',
  LU: 'north',
  LV: 'north',
  LY: 'north',
  MA: 'north',
  MC: 'north',
  MD: 'north',
  ME: 'north',
  MF: 'tropical',
  MG: 'south',
  MH: 'tropical',
  MK: 'north',
  ML: 'tropical',
  MM: 'north',
  MN: 'north',
  MO: 'north',
  MP: 'tropical',
  MQ: 'tropical',
  MR: 'north',
  MS: 'tropical',
  MT: 'north',
  MU: 'south',
  MV: 'tropical',
  MW: 'south',
  MX: 'north',
  MY: 'tropical',
  MZ: 'south',
  NA: 'south',
  NC: 'south',
  NE: 'tropical',
  NF: 'south',
  NG: 'tropical',
  NI: 'tropical',
  NL: 'north',
  NO: 'north',
  NP: 'north',
  NR: 'tropical',
  NU: 'south',
  NZ: 'south',
  OM: 'north',
  PA: 'tropical',
  PE: 'south',
  PF: 'south',
  PG: 'tropical',
  PH: 'tropical',
  PK: 'north',
  PL: 'north',
  PM: 'north',
  PN: 'south',
  PR: 'tropical',
  PS: 'north',
  PT: 'north',
  PW: 'tropical',
  PY: 'south',
  QA: 'north',
  RE: 'south',
  RO: 'north',
  RS: 'north',
  RU: 'north',
  RW: 'tropical',
  SA: 'north',
  SB: 'south',
  SC: 'tropical',
  SD: 'tropical',
  SE: 'north',
  SG: 'tropical',
  SH: 'south',
  SI: 'north',
  SJ: 'north',
  SK: 'north',
  SL: 'tropical',
  SM: 'north',
  SN: 'tropical',
  SO: 'tropical',
  SR: 'tropical',
  SS: 'tropical',
  ST: 'tropical',
  SV: 'tropical',
  SX: 'tropical',
  SY: 'north',
  SZ: 'south',
  TC: 'north',
  TD: 'tropical',
  TF: 'south',
  TG: 'tropical',
  TH: 'tropical',
  TJ: 'north',
  TK: 'south',
  TL: 'south',
  TM: 'north',
  TN: 'north',
  TO: 'south',
  TR: 'north',
  TT: 'tropical',
  TV: 'south',
  TW: 'north',
  TZ: 'tropical',
  UA: 'north',
  UG: 'tropical',
  UM: 'tropical',
  US: 'north',
  UY: 'south',
  UZ: 'north',
  VA: 'north',
  VC: 'tropical',
  VE: 'tropical',
  VG: 'tropical',
  VI: 'tropical',
  VN: 'tropical',
  VU: 'south',
  WF: 'south',
  WS: 'south',
  XK: 'north',
  YE: 'tropical',
  YT: 'south',
  ZA: 'south',
  ZM: 'south',
  ZW: 'south',
}

export function hemisphereFromRegion(
  regionCode: string | null | undefined
): Hemisphere {
  if (!regionCode) return 'north'
  const code = regionCode.toUpperCase()
  return COUNTRY_HEMISPHERE[code] ?? 'north'
}

export function hemisphereFromLatitude(lat: number): Hemisphere {
  if (lat > 23.5) return 'north'
  if (lat < -23.5) return 'south'
  return 'tropical'
}

export function seasonFor(date: Date, hemisphere: Hemisphere): Season {
  const month = date.getMonth()
  const northern: Season =
    month <= 1 || month === 11
      ? 'winter'
      : month <= 4
        ? 'spring'
        : month <= 7
          ? 'summer'
          : 'fall'
  if (hemisphere !== 'south') return northern
  switch (northern) {
    case 'winter':
      return 'summer'
    case 'spring':
      return 'fall'
    case 'summer':
      return 'winter'
    case 'fall':
      return 'spring'
  }
}
